version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
#        working directory: ~/All_work/Reproducibility of Scientific Research/Project
        working directory: ~/Tech-RoSR-2018/Test
        steps:
            - run: 
                name: create html from ipynb on Windows
                command: ./run_win.sh
            - run: 
                name: create html from ipynb on MacOS
                command: ./run_MacOS.sh
            - store_artifacts:
                path: .
                destination: .