version: 2
jobs:
    build:
        docker:
            # - image: circleci/python:3.7.0
            - image: continuumio/miniconda3 
        steps:
            - checkout 
            # - run: 
                # name: Create environment
                # command: sh ./run_ci_env.sh
                # working_directory: Test
            # - run: 
                # name: Create html from ipynb
                # command: sh ./run_ci_conv.sh
                # working_directory: Test
            - run:
                name: Create html from ipynb
                command: sh ./run_CI.sh
                working_directory: Test
            - store_artifacts:
                path: Test/Results