version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
        # working directory: ~/Tech-RoSR-2018
        steps:
            -run:
                name: Get ls
                command: ls > ls.txt
            - store_artifacts:
                path: .
                destination: .