version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.0
        steps:
            - checkout
            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
            - run: 
                name: Create environment
                command: sh ./run_ci_env.sh
            - run: 
                name: Create html from ipynb
                command: sh ./run_ci_conv.sh
            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
                paths:
                    - "venv"
            - store_artifacts:
                path: Results