version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
        working directory: ~/All_work/Reproducibility of Scientific Research/Project/Test
        # working directory: ~/Project/Test
        steps:
            - run: 
                name: Create html from ipynb on Windows
                command: ./run_win.sh
            - run: 
                name: Create html from ipynb on MacOS
                command: ./run_MacOS.sh
            - store_artifacts:
                path: .
                destination: .