version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.0
        steps:
            - checkout
            - restore_cache:
                key: deps1
            - run: 
                name: Create environment and api
                command: |
                    sh ./run_ci_env.sh
                    mkdir ~/.kaggle
                    echo $KaggleAPI > ~/.kaggle/kaggle.json
            - run: 
                name: Download solution and upload to osf
                command: |
                    . venv/bin/activate
                    cd kaggle/input
                    kaggle competitions download --force titanic
                    cd ../src
                    jupyter nbconvert --execute titanic.ipynb
                    export OSF_PASSWORD
                    osf -u vladimirzyuzin@yandex.ru -p x783r upload answer_osf.csv osfstorage/Zyuzin/answer_osf.csv
            - save_cache:
                key: deps1
                paths:
                    - "venv"
            - store_artifacts:
                path: Results