version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.0
        steps:
            - checkout 
            - run: 
                name: Create environment
                command: sh ./run_ci_env.sh
            - run: 
                name: Create html from ipynb
                command: sh ./run_ci_conv.sh
            - store_artifacts:
                path: Results