version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.0
        steps:
            - checkout
            - restore_cache:
                key: deps1
            - run: 
                name: Create environment and api
                command: |
                    sh ./run_ci_env.sh
                    mkdir ~/.kaggle
                    echo $KaggleAPI > ~/.kaggle/kaggle.json
            - run: 
                name: Download solution
                command: |
                    . venv/bin/activate
                    cd kaggle
                    mkdir input
                    cd input
                    kaggle competitions download titanic
                    cd ../src
                    jupyter nbconvert --execute titanic.ipynb
                    kaggle competitions submit titanic -f answer.csv -m "solution with circle and binder"
            - save_cache:
                key: deps1
                paths:
                    - "venv"
            - store_artifacts:
                path: Results