version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
        steps:
            - checkout 
            - run: 
                name: Create html from ipynb on Windows
                command: sh ./run_win.sh
                working_directory: Test
            - run: 
                name: Create html from ipynb on MacOS
                command: ./run_MacOS.sh
                working_directory: Test
            - store_artifacts:
                path: .