version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.6.1
        working directory: ~/Tech-RoSR-2018
        steps:
            - checkout 
            - run: 
                name: Create html from ipynb on Windows
                command: |
                    cd Test/
                    ./run_win.sh
            - run: 
                name: Create html from ipynb on MacOS
                command: |
                    cd Test/
                    ./run_MacOS.sh
            - store_artifacts:
                path: .